
output$home_summary <- renderUI({HTML("<b> change all this text to clickable icons. automatically start with sidebar closed and use this as the initial navigation?</b><br><br><br>All the data in this app is simulated, and so don't represent the true proportions. The sample sizes of the police divisions are accurate, and so the method for determining confidence intervals remains correct, and in line with the stats testing tool.<br><br>Use the menu to the left to navigate<br><b>Crime Victimisation Rate</b><br>This can be used to show how crime rates have changed over the course of the SCJS, and how this varies by police division.<br><br><b>Confidence in Police</b><br>Use this tool to compare SCJS respondents' confidence in the police, and look at how police divisions compare with one another, and how they have changed across time<br><br><b>Other stuff</b><br>Additionally, there are many other variables available for visualisation in the 'other stuff' tab.<br><br><b>Tables</b><br>Using the Tables tab, you can select variables of interest and different police divisions, and create a custom table which you can download. This table will automatically test whether the most recent survey found a significant change from the previous survey year, and from the first survey year.<br><br><b>Help & Information</b><br>We include some information on how proportion tests are calculated for the SCJS, and there is handy stats testing tool which allows you to test whether two proportions are significantly different from one another.")})

output$trend_summary <- renderUI({HTML("<b>Visualising Trends</b><br><br>Here you can visualise the trends over time of various questions of the survey.<br><br>Choose an area of the survey to focus on, and then explore the variables which the SCJS collects in that area.<br> By selecting different police divisions, you can see how trends have varied for different areas.<br><br>You can also change whether you want to see confidence intervals, or the legend.<br><br>Information regarding confidence intervals and sample sizes is available when hovering the mouse over a line on the plot.<br>If you wish to find out whether a difference is significant or not, head to the comparison tool.")})

output$compare_summary <- renderUI({HTML("Here you can compare sets of variables from the SCJS (e.g. confidence in the local police) across different police divisions, and across different years.<br><br>By using the selection boxes below, you can compare one division with another, or the same division across different years.<br><br>When two <b>adjacent</b> percentages are significantly different from one another, the higher will be coloured green, and the lower red.<br><br>Grey coloured bars indicate that there is no significant difference between the two.")})

output$stt_summary <- renderUI({HTML("This tool replicates the excel workbook found on <a href='http://www.gov.scot/Topics/Statistics/Browse/Crime-Justice/Datasets/SCJS/SCJS201617StatsTestingTool'>the Scottish Crime & Justice Survey (SCJS) website.</a><br><br>SCJS estimates are based on a representative sample of the population of Scotland aged 16 or over living in private households. A sample, as used in the SCJS, is a small-scale representation of the population from which it is drawn.<br><br>Any sample survey may produce estimates that differ from the values that would have been obtained if the whole population had been interviewed. The magnitude of these differences is related to the size and variability of the estimate, and the design of the survey, including sample size.<br><br>It is however possible to calculate the range of values between which the population figures are estimated to lie; known as the confidence interval (also referred to as margin of error). At the 95 per cent confidence level, when assessing the results of a single survey it is assumed that there is a one in 20 chance that the true population value will fall outside the 95 per cent confidence interval range calculated for the survey estimate. Similarly, over many repeats of a survey under the same conditions, one would expect that the confidence interval would contain the true population value 95 times out of 100.<br><br>Because of sampling variation, changes in reported estimates between survey years or between population subgroups may occur by chance. In other words, the change may simply be due to which respondents were randomly selected for interview.<br><br>Whether this is likely to be the case can be assessed using standard statistical tests. These tests indicate whether differences are likely to be due to chance or represent a real difference. In general, only differences that are statistically significant at the five per cent level (and are therefore likely to be real as opposed to occurring by chance) are reported.")})


