help_page <- div(id="helpinfo",
    div(class="helptext",id="hi1",
        tags$h5("SCJS Questions"),
        tags$p("To calculate percentages of, for example, survey respondents expressing confidence in the local police, categories of responses to survey questions have been combined (e.g. Confidence includes those responding 'Fairly Confident' and 'Very Confident'). For the few exceptional questions (such as perceiving the 'same or less' crime), care has been taken in the labels and information-on-hover to reflect this. More information and the entire questionnaire can be found on ",tags$a(target="_blank",tags$ins("the SCJS publication page."),href="http://www.gov.scot/Topics/Statistics/Browse/Crime-Justice/crime-and-justice-survey/publications"))
    ),
    
    div(class="helptext",id="hi2",
        tags$h5("Confidence Intervals, Rounding, and Statistical Testing"),
        tags$p("SCJS estimates are based on a representative sample of the population of Scotland aged 16 or over living in private households. A sample, as used in the SCJS, is a small-scale representation of the population from which it is drawn. Any sample survey may produce estimates that differ from the values that would have been obtained if the whole population had been interviewed. The magnitude of these differences is related to the size and variability of the estimate, and the design of the survey, including sample size. It is however possible to calculate the range of values between which the population figures are estimated to lie; known as the confidence interval (also referred to as margin of error). At the 95 per cent confidence level, when assessing the results of a single survey it is assumed that there is a one in 20 chance that the true population value will fall outside the 95 per cent confidence interval range calculated for the survey estimate. Similarly, over many repeats of a survey under the same conditions, one would expect that the confidence interval would contain the true population value 95 times out of 100. Because of sampling variation, changes in reported estimates between survey years or between population subgroups may occur by chance. In other words, the change may simply be due to which respondents were randomly selected for interview. Whether this is likely to be the case can be assessed using standard statistical tests. These tests indicate whether differences are likely to be due to chance or represent a real difference. In general, only differences that are statistically significant at the five per cent level (and are therefore likely to be real as opposed to occurring by chance) are reported."),
        tags$p("The method for the in-built testing here (color coding red/green/grey) is explained on the SCJS website, where there is",tags$a(target="_blank",tags$ins("an excel workbook"),href="http://www.gov.scot/Topics/Statistics/Browse/Crime-Justice/Datasets/SCJS/SCJS201617StatsTestingTool"), "for users to conduct these tests themselves."),
        tags$p("All proportions/percentages and confidence intervals presented here are rounded to 1 decimal place. However, the in-built testing (which colours visual elements red/green/grey accordingly) uses",tags$b("unrounded"),"proportions. Users should be aware, when conducting their own tests via the tool provided on the SCJS website, that using rounded proportions may yield slightly different results to those displayed here.")
    )
)