help_page <- div(id="helpinfo",
    div(class="helptext",id="hi1",
        tags$h5("SCJS Questions and Responses"),
        tags$p("The results here represent percentages of responses to different questions in the questionnaire. These percentages are weighted for the unequal probability of selection for interview caused by the sample design. The visualisations included here allow for these results to be broken down by the Police Divisions in which respondents lived at the time of interview. Although this can show how experiences/attitudes vary between Police Divisions, there may be complex explanations underlying these differences. For example, more urban areas may contain more deprived areas, a greater proportion of younger adults, more social renters and so on – all of which may influence results for that Police Division rather than or in addition to factors like the performance of the police. In that sense, whilst the visualisations here are helpful for highlighting how views and experiences differ across Scotland, they do not necessarily explain the reasons for such differences or indicate that one area is better than another."),
        tags$p("Additionally, it is important to consider the absolute results as well as any relative differences or changes. For example, the vast majority of people may hold a positive view, even if this has fallen a little over time or is lower in one area than another. This is an important point to note when interpreting and summarising findings."),
        tags$p("Take care to ensure that interpretation of the results is accurate. The percentages reported here often represent several categories of possible responses combined (e.g. Confidence in the police includes those responding 'Fairly Confident' and 'Very Confident'). Care has been taken in the visualisations and information-on-hover to reflect this. More information, along with the reports and entire questionnaire can be found on ",tags$a(target="_blank",tags$ins("the SCJS publication page."),href="http://www.gov.scot/Topics/Statistics/Browse/Crime-Justice/crime-and-justice-survey/publications"))
    ),
    
    div(class="helptext",id="hi2",
        tags$h5("Confidence Intervals, Rounding, and Statistical Testing"),
        tags$p("SCJS estimates are based on a representative sample of the population of Scotland aged 16 or over living in private households. A sample, as used in the SCJS, is a small-scale representation of the population from which it is drawn. Any sample survey may produce estimates that differ from the values that would have been obtained if the whole population had been interviewed. The magnitude of these differences is related to the size and variability of the estimate, and the design of the survey, including sample size. It is however possible to calculate the range of values between which the population figures are estimated to lie; known as the confidence interval (also referred to as margin of error). At the 95 per cent confidence level, when assessing the results of a single survey it is assumed that there is a one in 20 chance that the true population value will fall outside the 95 per cent confidence interval range calculated for the survey estimate. Similarly, over many repeats of a survey under the same conditions, one would expect that the confidence interval would contain the true population value 95 times out of 100. Because of sampling variation, changes in reported estimates between survey years or between population subgroups may occur by chance. In other words, the change may simply be due to which respondents were randomly selected for interview. Whether this is likely to be the case can be assessed using standard statistical tests. These tests indicate whether differences are likely to be due to chance or represent a real difference. In general, only differences that are statistically significant at the five per cent level (and are therefore likely to be real as opposed to occurring by chance) are reported."),
        tags$p("The method for the in-built testing here (color coding blues/grey) is explained on the SCJS website, where there is",tags$a(target="_blank",tags$ins("an excel workbook"),href="http://www.gov.scot/Topics/Statistics/Browse/Crime-Justice/Datasets/SCJS/SCJS201617StatsTestingTool"), "for users to conduct these tests themselves."),
        tags$p("All proportions/percentages and confidence intervals presented here are rounded to 1 decimal place. However, the in-built testing (which colours visual elements blues/grey accordingly) uses",tags$b("unrounded"),"proportions. Users should be aware, when conducting their own tests via the tool provided on the SCJS website, that using rounded proportions may yield slightly different results to those displayed here.")
    )
)